pipeline {
    agent any
    stages {
        stage('Create Environment') {
            steps {
                sh '''
                python3 -m venv ansible
                source ansible/bin/activate
                pip3 install -r requirements.txt
                '''
            }
        }
        stage('Execute ansible playbook') {
            steps{
                withCredentials([string(credentialsId: 'ansible-secret', variable: 'passwd')]) {
                    echo "> Running playbook"
                    sh '''
                    source ansible/bin/activate
                    ansible-playbook ansible-fortigate/app2.yaml --extra-vars "passwd=$passwd"
                    '''
                }
            }
        }
    }
}